### ISSUE TITLE
My Rprofile has encoding issues

### ISSUE THREAD

**Issue by Diego-MX** [HenrikBengtsson/startup#132]
I have created a function that I use all the time: 

```str_delatinize <- function (x) chartr("ÁÉÍÓÚÑáéíóúñ", "AEIOUNaeioun", x)```

The issue with this function is the latin characters that are not encoded correctly when sourced via different channels.  From what I read this issue is more present in Windows than other systems, but I can't verify it. 

When sourced incorrectly this function shows the following error: 
```
Error in chartr("Ã\201Ã‰Ã\215Ã“ÃšÃ‘Ã¡Ã©Ã­Ã³ÃºÃ±", "AEIOUNaeioun", x) :
  'old' is longer than 'new'
```
All the latin characters are encoded weirdly, and actually this is the reason to delatinize them.  

When _sourcing_ this directly, I can pass an `encoding` parameter like so: 
```
source("file_with_function.R", encoding="utf-8")
```

Is there a way to pass `encoding` parameter when calling `startup::startup()`? 

Thank you.

**Comment by HenrikBengtsson** [comment]
I've added argument `encoding` to `startup()`, e.g.

```r
startup::startup(encoding = "utf-8")
```

Could you please try with the version in the develop branch, i.e.

```r
remotes::install_github("HenrikBengtsson/startup", ref = "develop")
```

**Comment by HenrikBengtsson** [comment]
I haven't heard back, but I'll assume my fix addresses this problem.
